name: Blog CI

on:  
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          repository: preinpost/mdBook
          path: ${GITHUB_WORKSPACE}/mdbook

      - uses: actions/checkout@v3

      - name: check ls 1
        run: ls -al
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run build mdbook
        run: cargo build --release  
        working-directory: ${GITHUB_WORKSPACE}/mdbook

      - name: check ls 2
        run: ls -al


      
      - name: check ls 3
        run: ls -al
      
      - name: cp mdbook
        run: cp ${GITHUB_WORKSPACE}/mdbook/target/release/mdbook ${GITHUB_WORKSPACE}

      - name: Run mdbook
        run: ./mdbook build