name: Blog CI

on:  
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          name: preinpost/mdBook
          ref: refs/heads/master

      - run: ls -al
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
        env:
          working-directory: ./work/preinpost.github.io

      - uses: actions/checkout@v3
      - run: ./target/release/mdbook build
