name: Blog CI

on:  
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          repository: preinpost/mdBook
          path: ./mdbook

      - run: ls -al
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: build mdbook
        run: cargo build --release --project-dir ./mdbook

      - uses: actions/checkout@v3
      - run: .mdbook/target/release/mdbook build
